version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: railfood-frontend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    restart: unless-stopped