version: '3.8'

services:
  frontend:
    build: .
    container_name: railfood-frontend
    ports:
      - "80:80"  # IPv4 and IPv6
      - "443:443"  # IPv4 and IPv6
    volumes:
      - /root/railfood-main1/webroot:/usr/share/nginx/html/.well-known/acme-challenge
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped