# HTTP server (redirects to HTTPS)
server {
  listen 80;
  listen [::]:80;
  server_name thehappyjourneyy.com www.thehappyjourneyy.com;

  # Let’s Encrypt challenge
  location /.well-known/acme-challenge/ {
    root /usr/share/nginx/html;
  }

  # Redirect all HTTP traffic to HTTPS
  return 301 https://$host$request_uri;
}

# HTTPS server
server {
  listen 443 ssl;
  server_name thehappyjourneyy.com www.thehappyjourneyy.com;

  ssl_certificate /etc/letsencrypt/live/thehappyjourneyy.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/thehappyjourneyy.com/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
    expires 1M;
    access_log off;
    add_header Cache-Control "public";
  }

  location ~* \.(?:css|js)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
  }
}