server {
    listen 80;
    listen [::]:80;  # Include for IPv6 support
    server_name thehappyjourneyy.com www.thehappyjourneyy.com;
    root /root/railfood-main1/webroot;
    location /.well-known/acme-challenge/ {
        allow all;
        try_files $uri $uri/ =404;
    }
    location / {
        # Proxy to Docker container, if applicable
        proxy_pass http://localhost:3000;  # Adjust port based on your Docker setup
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}